---
# This playbook will copy over Memcache from the Control Machine Repository to the target machine and install the software from source

- name: Create install_soft directory to hold the installers
  file: path={{ install_temp_directory }} owner={{ instance_owner }} group={{ instance_owner }} mode=0755 state=directory

- name: Verify if libevent , libevent-devel , libevent-doc , libevent-headers are present. If not install it
  yum: pkg={{ item }} state=present
  with_items:
   - libevent
   - libevent-devel
   - libevent-doc
   - libevent-headers

- group: name={{ memcache_service_group }} state=present
- user: name={{ memcache_service_owner }} comment="Memcached Service User" group={{ memcache_service_group }}

- name: Copy installers from Control Machine to Target Machine
  copy: src={{ playbook_dir }}/roles/memcache/files/ dest={{ install_temp_directory }} mode=0664

- name: Unpack Memcache source files
  shell: cd {{ install_temp_directory }} && tar -xzvf {{ memcachesrc }}.tar.gz creates={{ install_temp_directory }}/{{ memcachesrc }}

- name: Configure Memcache with default options
  shell: cd {{ install_temp_directory }}/{{ memcachesrc }} && ./configure creates={{ install_temp_directory }}/{{ memcachesrc }}/Makefile

- name: Make - Memcache
  shell: cd {{ install_temp_directory }}/{{ memcachesrc }} && make creates={{ install_temp_directory }}/{{ memcachesrc }}/memcached-debug

- name: Make install - Memcache
  shell: cd {{ install_temp_directory }}/{{ memcachesrc }} && make install

- name: Setup Memcached sysconfig file from template
  template: src=memcached_sysconfig.j2 dest=/etc/sysconfig/memcached

- name: Install Memcache init script from template
  template: src=memcached_init.j2 dest=/etc/init.d/memcached mode=0755  

- name: Create memcached directory for the runtime
  file: path={{ memcache_run_directory }} owner={{ memcache_service_owner }} group={{ memcache_service_group }} mode=0755 state=directory recurse=yes

- name: Start Memcached service with default settings 
  shell: echo "Starting Memcached"
  notify: Start memcached