---
 - name: Start Nginx 
   shell: cd {{ nginx_prefix }}/sbin && ./nginx

 - name: Stop Nginx  
   shell: cd {{ nginx_prefix }}/sbin && ./nginx -s stop

 - name: Restart Nginx
   shell: cd {{ nginx_prefix }}/sbin && ./nginx -s stop && sleep 5 && ./nginx