---
#This playbook will Restart the Apache Web Server. 
# Apache Web Server Install is a pre-requisite for this playbook to run.

- hosts: all
  remote_user: openplatform
  sudo: True


  tasks:
  - name: Restart Apache
    shell: cd {{ apache_prefix }}/bin && ./apachectl -k restart