---
#This playbook will install the Apache web server on the AWS Cloud.

- include: provisioners/aws-standalone-apache-php.yml

- hosts: aws
  sudo: True

  roles: 
    - apache
    - php
    - cleanup